version: "3.8"

services:
  ubuntu:
    tty: true
    build: .
    deploy:
      resources:
        limits:
          memory: 800M
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8081:8081
    volumes:
      - "${HOME}/.zsh_history:/home/ubuntu/.zsh-histoy"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "C:/Users/marco/OneDrive/Área de Trabalho/angry:/home/ubuntu/work"
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    deploy:
      resources:
        limits:
          memory: 800M
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
